name: eclipse-temurin-25-alpine
on: 
  schedule:
    - cron: '28 3 * * *'
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-26.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/mirror-dhi
        with:
          dhi-tag: 'eclipse-temurin:25-alpine'
          docker-tag: 'folioci/eclipse-temurin:25-alpine'
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
